# If we want to use the database, uncomment the lines. The database is used to save logs, files, monitor data and secret keys but is not necessary for the application to run.

services:
  langflow:
    image: langflowai/langflow:latest
    ports:
      - '7860:7860'
    # depends_on:
    #   - postgres
    environment:
      # - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow
      - DO_NOT_TRACK=true
    volumes:
      - langflow-data:/app/langflow

  # postgres:
  #   image: postgres:16
  #   environment:
  #     POSTGRES_USER: langflow
  #     POSTGRES_PASSWORD: langflow
  #     POSTGRES_DB: langflow
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - langflow-postgres:/var/lib/postgresql/data

volumes:
  # langflow-postgres:
  langflow-data:
